// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://djzwuqnrcgyirlkhstgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqend1cW5yY2d5aXJsa2hzdGdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTIyNjAsImV4cCI6MjA3MzE4ODI2MH0.nQpN-a2GIN44sKKZMdWQkU9N_WZ8ADqjnqiy0_xT8R8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);